name: Validate

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  miri:
    name: Miri

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        features:
          - ""
          - --features nightly

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Rust
        run: |
          rustup toolchain install nightly --profile minimal --component miri,rust-src --allow-downgrade
          rustup default nightly
      - name: Test
        run:
          cargo miri test --workspace ${{ matrix.features }} --all-targets --no-fail-fast
